# -*- coding:utf-8 -*-
# UnigramAccess: Static data, localization dictionaries, and UI label mappings.
#
# Note: When adding new language entries to any dictionary, please keep the
# language codes sorted alphabetically (e.g., 'ar', 'de', 'en', 'fa', 'ru', ...).

# ============================================================================
# 1. MESSAGE HISTORY & FORMATTING
# ============================================================================

# Keywords for parsing message elements in the chat history (read status, time, and sender).
# Format per language code:
#   "lang_code": (
#       [0] read status phrase (e.g. ". Seen"),
#       [1] unread status phrase (e.g. ". Not seen"),
#       [2] sent message prefix / timestamp separator (e.g. ", Sent at "),
#       [3] received message prefix / timestamp separator (e.g. ", Received at "),
#       [4] leading phrase before sent message text (usually identical to [2]),
#       [5] leading phrase before received message text (usually identical to [3]),
#   )
keywordsInMessages = {
	'ar': ('. تم قرائتها', '. غير مقروءة', ', تم الإرسال الساعة ', ', تم التسليم الساعة ', ', تم الإرسال الساعة ', ', تم التسليم الساعة '),
	'be': ('. Прагледжана', '. Не прагледжана', ', Адпраўлена а ', ', Атрымана а ', ', Адпраўлена а ', ', Атрымана а '),
	'ca': ('. Llegit', '. Per llegir', ', Enviat el a les ', ', Rebut a les ', ', Enviat el a les ', ', Rebut a les '),
	'cs': ('. Viděno', '. Neviděno', ', Odesláno v ', ', Přijato v ', ', Odesláno v ', ', Přijato v '),
	'de': ('. Gesehen', '. Noch nicht gesehen', ', Gesendet um ', ', Empfangen um ', ', Gesendet um ', ', Empfangen um '),
	'en': ('. Seen', '. Not seen', ', Sent at ', ', Received at ', ', Sent at ', ', Received at '),
	'es': ('. Visto', '. No visto', ', Enviado a las ', ', Recibido el a las ', ', Enviado a las ', ', Recibido el a las '),
	'fa': ('. دیده شده', '. دیده نشده', 'ارسال شد', 'دریافت شد', ', \u2068در \u2068', ', \u2068در \u2068'),
	'fi': ('. Nähty', '. Ei nähty', ', Lähetetty klo ', ', Vastaanotettu klo ', ', Lähetetty klo ', ', Vastaanotettu klo '),
	'fr': ('. Vu', '. Non vu', ', Envoyé à ', ', Reçu à ', ', Envoyé à ', ', Reçu à '),
	'he': ('. נצפה', '. לא נצפה', ', נשלח ב־ ', ', התקבל ב־ ', ', נשלח ב־ ', ', התקבל ב־ '),
	'hr': ('. Viđeno', '. Nije viđeno', ', Poslano u ', ', Preuzeto u ', ', Poslano u ', ', Preuzeto u '),
	'hu': ('. Olvasott', '. Olvasatlan', ', Elküldve ', ', Beérkezett ', ', Elküldve ', ', Beérkezett '),
	'id': ('. Dilihat', '. Tidak dilihat', ', Kirim pada ', ', Diterima pada ', ', Kirim pada ', ', Diterima pada '),
	'it': ('. Visto', '. Non visto', ', Inviato alle ', ', Ricevuto alle ', ', Inviato alle ', ', Ricevuto alle '),
	'kk': ('. Көрілді', '. Көрілмеді', 'жіберілді', 'келіп түсті', ', ', ', '),
	'ko': ('. 접속함', '. 접속 안 함', '보냄', '받음', ', ', ', '),
	'ms': ('. Dilihat', '. Tak kelihatan', ', Kirim ', ', Terima ', ', Kirim ', ', Terima '),
	'nb': ('. Sett', '. Ikke sett', ', Sendt kl. ', ', Mottatt kl. ', ', Sendt kl. ', ', Mottatt kl. '),
	'nl': ('. Gezien', '. Niet gezien', ', Gestuurd om ', ', Ontvangen om ', ', Gestuurd om ', ', Ontvangen om '),
	'pl': ('. Wyświetlono', '. Nie wyświetlono', ', Wysłana o ', ', Odebrane o ', ', Wysłana o ', ', Odebrane o '),
	'pt-br': ('. Lido', '. Não lido', ', Enviado às ', ', Recebido às ', ', Enviado às ', ', Recebido às '),
	'ro': ('. Văzut', '. Nu a fost văzut', ', Trimis la ', ', A primit la ', ', Trimis la ', ', A primit la '),
	'ru': ('. Прочитано', '. Не прочитано', ', Отправлено в ', ', Получено в ', ', Отправлено в ', ', Получено в '),
	'sk': ('. Videné', '. Nevidené', ', Odoslať o ', ', Prijaté o ', ', Odoslať o ', ', Prijaté o '),
	'sr': ('. Виђено', '. Није виђено', ', Послато у ', ', Примљено у ', ', Послато у ', ', Примљено у '),
	'sv': ('. Sedd', '. Ej sedd', ', Skickad kl. ', ', Mottaget kl. ', ', Skickad kl. ', ', Mottaget kl. '),
	'tr': ('. Görüldü', '. Görülmedi', 'tarihinde gönderildi', 'tarihinde alındı', ', bugün ', ', bugün '),
	'uk': ('. Прочитане', '. Непрочитане', ', Надіслано ', ', Отримано ', ', Надіслано ', ', Отримано '),
	'uz': ('. Oʻqilgan', '. Oʻqilmagan', 'ga yuborish', 'qabul qilindi', ', da ', ', da '),
	'zh-hans': ('. 已读', '. 未读', ', 已发送于 ', ', 已收到 ', ', 已发送于 ', ', 已收到 '),
	'zh-hant': ('. 已讀', '. 未讀', ', 傳送於 今天 ', ', 收到了 今天 ', ', 傳送於 今天 ', ', 收到了 今天 '),
}

# Administrator and owner rank badges in community messages.
# Format: "lang_code": ("AdminTitle", "OwnerTitle")
phrase_administrator_in_message = {
	'ar': ('المشرف', 'المالك'),
	'be': ('Кіраўнік', 'Уладальнік'),
	'ca': ('Administrador', 'Propietari'),
	'cs': ('Správce', 'Vlastník'),
	'de': ('Admin', 'Inhaber'),
	'en': ('Admin', 'Owner'),
	'es': ('Admin.', 'Propietario'),
	'fa': ('مدیر', 'مالک'),
	'fi': ('Valvoja', 'Omistaja'),
	'fr': ('Administrateur', 'Propriétaire'),
	'he': ('מנהל', 'בעלים'),
	'hr': ('Admin', 'Vlasnik'),
	'hu': ('Admin', 'Tulajdonos'),
	'id': ('Admin', 'Pemilik'),
	'it': ('Amministratore', 'Proprietario'),
	'kk': ('Әкімші', 'Иесі'),
	'ko': ('관리자', '소유자'),
	'ms': ('Pentadbir', 'Pemilik'),
	'nb': ('Administrator', 'Eier'),
	'nl': ('Beheerder', 'Eigenaar'),
	'pl': ('Admin', 'Właściciel'),
	'pt-br': ('Admin', 'Dono'),
	'ro': ('Admin', 'Proprietar'),
	'ru': ('Админ', 'Владелец'),
	'sk': ('Správca', 'Vlastník'),
	'sr': ('Админ', 'Власник'),
	'sv': ('Admin', 'Ägare'),
	'tr': ('Yönetici', 'Sahibi'),
	'uk': ('Адмін', 'Власник'),
	'uz': ('Admin', 'Ega'),
	'zh-hans': ('管理员', '所有者'),
	'zh-hant': ('管理員', '擁有者'),
}

# Separator text for unread messages divider in chat history.
# Format: "lang_code": ("keyword", ...)
unread_messages_keywords = {
	'ar': ('الرسائل غير المقروءة',),
	'be': ('непрачытаныя паведамленні',),
	'ca': ('missatges per llegir',),
	'cs': ('nepřečtené zprávy',),
	'de': ('ungelesene nachrichten',),
	'en': ('unread messages',),
	'es': ('mensajes no leídos',),
	'fa': ('پیام\u200cهای خوانده نشده', 'پیام های خوانده نشده', 'پیامهای خوانده نشده'),
	'fi': ('uudet viestit',),
	'fr': ('messages non lus',),
	'he': ('הודעות שלא נקראו',),
	'hr': ('nepročitane poruke',),
	'hu': ('olvasatlan üzenetek',),
	'id': ('pesan belum dibaca',),
	'it': ('messaggi non letti',),
	'kk': ('жаңа',),
	'ko': ('안 읽은 메시지',),
	'ms': ('mesej belum dibaca',),
	'nb': ('uleste meldinger',),
	'nl': ('ongelezen berichten',),
	'pl': ('nieprzeczytane wiadomości',),
	'pt-br': ('mensagens não lidas',),
	'ro': ('mesaje necitite',),
	'ru': ('непрочитанные сообщения',),
	'sk': ('neprečítané správy',),
	'sr': ('непрочитане поруке',),
	'sv': ('olästa meddelanden',),
	'tr': ('okunmamış mesajlar',),
	'uk': ('непрочитані повідомлення',),
	'uz': ('o‘qilmagan xabarlar',),
	'zh-hans': ('未读消息',),
	'zh-hant': ('未讀訊息',),
}


# ============================================================================
# 2. COMPOSER HEADER & INPUT FIELD
# ============================================================================

# Action type for the cancel button above the message input field (reply vs edit).
# Format: "action": {"lang_code": ("keyword", ...)}
composer_header_cancel_types = {
	'edit': {
		'ar': ('إلغاء التعديل', 'تحرير'),
		'be': ('скасаваць рэдагаванне', 'рэдагаваць'),
		'ca': ("cancel·la l'edició", 'edita'),
		'cs': ('zrušit editaci', 'upravit'),
		'de': ('bearbeitung abbrechen', 'bearbeiten'),
		'en': ('cancel editing', 'edit'),
		'es': ('cancelar edición', 'editar'),
		'fa': ('لغو ویرایش', 'ویرایش'),
		'fi': ('peruuta muokkaus', 'muokkaa'),
		'fr': ("annuler l'édtion", 'modifier'),
		'he': ('בטל עריכה', 'ערוך'),
		'hr': ('otkaži uređivanje', 'uredi'),
		'hu': ('szerkesztés megszakítása', 'szerkesztés'),
		'id': ('batalkan perubahan', 'edit'),
		'it': ('annulla modifica', 'modifica'),
		'kk': ('өңдеуді болдырмау', 'өңдеу'),
		'ko': ('편집 취소', '수정'),
		'ms': ('batal penyuntingan', 'sunting'),
		'nb': ('avbryt redigering', 'rediger'),
		'nl': ('bewerken annuleren', 'bewerken'),
		'pl': ('anuluj edycję', 'edytuj'),
		'pt-br': ('cancelar edição', 'editar'),
		'ro': ('anulează editarea', 'editează'),
		'ru': ('отмена редактирования', 'изменить'),
		'sk': ('zrušiť úpravy', 'upraviť'),
		'sr': ('откажите уређивање', 'уреди'),
		'sv': ('avbryt redigering', 'redigera'),
		'tr': ('düzenlemeyi iptal et', 'düzenle'),
		'uk': ('відхилити зміни', 'змінити'),
		'uz': ('tahrirlashni bekor qilish', 'tahrirlash'),
		'zh-hans': ('取消编辑', '编辑'),
		'zh-hant': ('取消編輯', '編輯'),
	},
	'reply': {
		'ar': ('إلغاء الرد', 'رد'),
		'be': ('скасаваць адказ', 'адказаць'),
		'ca': ('cancel·la la resposta', 'respon'),
		'cs': ('zrušit odpověď', 'odpovědět'),
		'de': ('antwort abbrechen', 'antworten'),
		'en': ('cancel reply', 'reply'),
		'es': ('cancelar respuesta', 'responder'),
		'fa': ('لغو پاسخ', 'پاسخ'),
		'fi': ('peruuta vastaus', 'vastaa'),
		'fr': ('annuler la réponse', 'répondre'),
		'he': ('בטל תגובה', 'הגב'),
		'hr': ('otkaži odgovaranje', 'odgovori'),
		'hu': ('válasz megszakítása', 'válasz'),
		'id': ('batal balas', 'balas'),
		'it': ('annulla risposta', 'rispondi'),
		'kk': ('жауап бермеу', 'жауап'),
		'ko': ('답장 취소', '답장'),
		'ms': ('batal balas', 'balas'),
		'nb': ('avbryt svar', 'svar'),
		'nl': ('antwoord annuleren', 'antwoorden'),
		'pl': ('anuluj odpowiedź', 'odpowiedz'),
		'pt-br': ('cancelar resposta', 'responder'),
		'ro': ('anulează răspuns', 'răspunde'),
		'ru': ('отмена ответа', 'ответить'),
		'sk': ('zrušiť odpoveď', 'odpovedať'),
		'sr': ('откажите одговор', 'одговори'),
		'sv': ('avbryt svar', 'svara'),
		'tr': ('yanıtı iptal et', 'yanıtla'),
		'uk': ('скасування відповіді', 'відповісти'),
		'uz': ('javob berishni bekor qilish', 'javob yozish'),
		'zh-hans': ('取消回复', '回复'),
		'zh-hant': ('取消回覆', '回覆'),
	},
}

# Spoken replacement titles for composer headers to improve speech clarity.
# Format: "original_title": _("replacement_title")
composer_header_title_replacements = {
	"Edit": _("Editing"),
	"ویرایش": _("Editing"),
}


# ============================================================================
# 3. CHATS & DIALOGS
# ============================================================================

# Keywords for identifying chat entity type (channel, group, bot) in deletion/leave dialogs.
# Format: "entity_type": {"lang_code": ("keyword", ...)}
chat_deletion_keywords = {
	'bot': {
		'ar': ('بوت',),
		'be': ('бот',),
		'ca': ('bot',),
		'cs': ('bot',),
		'de': ('bot',),
		'en': ('bot',),
		'es': ('bot',),
		'fa': ('ربات',),
		'fi': ('botti',),
		'fr': ('bot',),
		'he': ('בוט',),
		'hr': ('bot',),
		'hu': ('bot',),
		'id': ('bot',),
		'it': ('bot',),
		'kk': ('бот',),
		'ko': ('봇',),
		'ms': ('bot',),
		'nb': ('robot',),
		'nl': ('bot',),
		'pl': ('bot',),
		'pt-br': ('bot',),
		'ro': ('robot',),
		'ru': ('бот',),
		'sk': ('bot',),
		'sr': ('бот',),
		'sv': ('bot',),
		'tr': ('bot',),
		'uk': ('бот',),
		'uz': ('bot',),
		'zh-hans': ('机器人',),
		'zh-hant': ('機器人',),
	},
	'channel': {
		'ar': ('مغادرة القناة',),
		'be': ('выйсці з канала',),
		'ca': ('abandona el canal',),
		'cs': ('opustit kanál',),
		'de': ('kanal verlassen',),
		'en': ('leave channel',),
		'es': ('salir del canal',),
		'fa': ('ترک کانال',),
		'fi': ('poistu kanavalta',),
		'fr': ('quitter le canal',),
		'he': ('עזוב ערוץ',),
		'hr': ('napusti kanal',),
		'hu': ('csatorna elhagyása',),
		'id': ('keluar channel',),
		'it': ('lascia il canale',),
		'kk': ('шығу',),
		'ko': ('채널 나가기',),
		'ms': ('keluar saluran',),
		'nb': ('forlat kanal',),
		'nl': ('kanaal verlaten',),
		'pl': ('opuść kanał',),
		'pt-br': ('sair do canal',),
		'ro': ('părăsește canalul',),
		'ru': ('покинуть канал',),
		'sk': ('opustiť kanál',),
		'sr': ('напусти канал',),
		'sv': ('lämna kanal',),
		'tr': ('kanaldan ayrıl',),
		'uk': ('покинути канал',),
		'uz': ('kanalni tark etish',),
		'zh-hans': ('退出频道',),
		'zh-hant': ('退出頻道',),
	},
	'group': {
		'ar': ('مغادرة المجموعة', 'حذف المجموعة ومغادرتها'),
		'be': ('выйсці з суполкі', 'выдаліць і выйсці з суполкі'),
		'ca': ('abandona el grup', 'elimina i abandona el grup'),
		'cs': ('opustit skupinu', 'smazat a opustit skupinu'),
		'de': ('gruppe verlassen', 'löschen und gruppe verlassen'),
		'en': ('leave group', 'delete and leave group'),
		'es': ('salir del grupo', 'eliminar y salir del grupo'),
		'fa': ('ترک گروه', 'حذف و ترک گروه'),
		'fi': ('poistu ryhmästä',),
		'fr': ('quitter le groupe', 'supprimer et quitter'),
		'he': ('עזוב קבוצה', 'מחק ועזוב קבוצה'),
		'hr': ('napusti grupu', 'izbriši i napusti grupu'),
		'hu': ('kilépés a csoportból', 'kilépés a csoportból és törlés'),
		'id': ('keluar grup', 'hapus dan keluar grup'),
		'it': ('lascia il gruppo', 'elimina e lascia'),
		'kk': ('шығу', 'жойып, шығу'),
		'ko': ('그룹 나가기', '그룹 삭제하고 나가기'),
		'ms': ('keluar grup', 'hapus dan keluar grup'),
		'nb': ('forlat gruppe', 'slett og forlat gruppen'),
		'nl': ('groep verlaten', 'groep verwijderen en verlaten'),
		'pl': ('opuść grupę', 'usuń i opuść grupę'),
		'pt-br': ('sair do grupo', 'apagar e sair do grupo'),
		'ro': ('părăsește grupul', 'șterge și părăsește grup'),
		'ru': ('покинуть группу', 'удалить и покинуть группу'),
		'sk': ('opustiť skupinu', 'odstrániť a opustiť skupinu'),
		'sr': ('напусти групу', 'избриши и напусти групу'),
		'sv': ('lämna grupp', 'ta bort och lämna grupp'),
		'tr': ('gruptan ayrıl', 'sil ve gruptan ayrıl'),
		'uk': ('покинути групу', 'видалити й покинути групу'),
		'uz': ('guruhni tark etish', 'oʻchirish va guruhni tark etish'),
		'zh-hans': ('退出群组', '删除并退出群组'),
		'zh-hant': ('退出群組', '刪除並退出群組'),
	},
}

# Window title of the Contacts dialog.
# Format: "lang_code": "title"
contacts_dialog_titles = {
	'ar': 'جهات الاتصال',
	'be': 'Кантакты',
	'ca': 'Contactes',
	'cs': 'Kontakty',
	'de': 'Kontakte',
	'en': 'Contacts',
	'es': 'Contactos',
	'fa': 'مخاطبین',
	'fi': 'Yhteystiedot',
	'fr': 'Contacts',
	'he': 'אנשי קשר',
	'hr': 'Kontakti',
	'hu': 'Névjegyek',
	'id': 'Kontak',
	'it': 'Contatti',
	'kk': 'Контакт',
	'ko': '연락처',
	'ms': 'Kenalan',
	'nb': 'Kontakter',
	'nl': 'Contacten',
	'pl': 'Kontakty',
	'pt-br': 'Contatos',
	'ro': 'Contacte',
	'ru': 'Контакты',
	'sk': 'Kontakty',
	'sr': 'Контакти',
	'sv': 'Kontakter',
	'tr': 'Kişiler',
	'uk': 'Контакти',
	'uz': 'Kontaktlar',
	'zh-hans': '联系人',
	'zh-hant': '聯絡人',
}


# ============================================================================
# 4. CONTEXT MENU & ACTIONS
# ============================================================================

# Option labels in the right-click context menu of messages and chats.
# Format: "action": {"lang_code": ("keyword", ...)}
context_menu_items = {
	'delete': {
		'ar': ('حذف', 'مغادرة القناة', 'مغادرة المجموعة', 'حذف المجموعة ومغادرتها', 'إلغاء الإرسال'),
		'be': ('выдаліць', 'выйсці з канала', 'выйсці з суполкі', 'выдаліць і выйсці з суполкі', 'скасаваць адпраўку'),
		'ca': ('elimina', 'abandona el canal', 'abandona el grup', 'elimina i abandona el grup', "cancel·la l'enviament"),
		'cs': ('smazat', 'opustit kanál', 'opustit skupinu', 'smazat a opustit skupinu', 'zrušit odesílání'),
		'de': ('löschen', 'kanal verlassen', 'gruppe verlassen', 'löschen und gruppe verlassen'),
		'en': ('delete', 'leave channel', 'leave group', 'delete and leave group', 'cancel sending'),
		'es': ('eliminar', 'salir del canal', 'salir del grupo', 'eliminar y salir del grupo', 'cancelar envío'),
		'fa': ('حذف', 'ترک کانال', 'ترک گروه', 'حذف و ترک گروه', 'لغو ارسال'),
		'fi': ('poista', 'poistu kanavalta', 'poistu ryhmästä', 'peruuta lähetys'),
		'fr': ('supprimer', 'quitter le canal', 'quitter le groupe', 'supprimer et quitter', "annuler l'envoi"),
		'he': ('מחק', 'עזוב ערוץ', 'עזוב קבוצה', 'מחק ועזוב קבוצה', 'בטל שליחה'),
		'hr': ('izbriši', 'napusti kanal', 'napusti grupu', 'izbriši i napusti grupu', 'prekini slanje'),
		'hu': ('törlés', 'csatorna elhagyása', 'kilépés a csoportból', 'kilépés a csoportból és törlés', 'küldés megszakítása'),
		'id': ('hapus', 'keluar channel', 'keluar grup', 'hapus dan keluar grup'),
		'it': ('elimina', 'lascia il canale', 'lascia il gruppo', 'elimina e lascia', 'annulla invio'),
		'kk': ('жою', 'шығу', 'жойып, шығу', 'жібермеу'),
		'ko': ('삭제', '채널 나가기', '그룹 나가기', '그룹 삭제하고 나가기', '보내기 취소'),
		'ms': ('hapus', 'keluar saluran', 'keluar grup', 'hapus dan keluar grup', 'batal kiriman'),
		'nb': ('slett', 'forlat kanal', 'forlat gruppe', 'slett og forlat gruppen', 'avbryt sending'),
		'nl': ('verwijderen', 'kanaal verlaten', 'groep verlaten', 'groep verwijderen en verlaten', 'versturen annuleren'),
		'pl': ('usuń', 'opuść kanał', 'opuść grupę', 'usuń i opuść grupę', 'anuluj wysyłanie'),
		'pt-br': ('apagar', 'sair do canal', 'sair do grupo', 'apagar e sair do grupo', 'cancelar o envio'),
		'ro': ('șterge', 'părăsește canalul', 'părăsește grupul', 'șterge și părăsește grup', 'anulează trimiterea'),
		'ru': ('удалить', 'покинуть канал', 'покинуть группу', 'удалить и покинуть группу', 'отменить отправку'),
		'sk': ('odstrániť', 'opustiť kanál', 'opustiť skupinu', 'odstrániť a opustiť skupinu'),
		'sr': ('избриши', 'напусти канал', 'напусти групу', 'избриши и напусти групу', 'откажи слање'),
		'sv': ('ta bort', 'lämna kanal', 'lämna grupp', 'ta bort och lämna grupp', 'avbryt sändning'),
		'tr': ('sil', 'kanaldan ayrıl', 'gruptan ayrıl', 'sil ve gruptan ayrıl'),
		'uk': ('видалити', 'покинути канал', 'покинути групу', 'видалити й покинути групу', 'скасувати надсилання'),
		'uz': ('oʻchirish', 'kanalni tark etish', 'guruhni tark etish', 'oʻchirish va guruhni tark etish', 'yuborishni bekor qilish'),
		'zh-hans': ('删除', '退出频道', '退出群组', '删除并退出群组'),
		'zh-hant': ('刪除', '退出頻道', '退出群組', '刪除並退出群組', '取消傳送'),
	},
	'edit': {
		'ar': ('تحرير',),
		'be': ('рэдагаваць',),
		'ca': ('edita',),
		'cs': ('upravit',),
		'de': ('bearbeiten',),
		'en': ('edit',),
		'es': ('editar',),
		'fa': ('ویرایش',),
		'fi': ('muokkaa',),
		'fr': ('modifier',),
		'he': ('ערוך',),
		'hr': ('uredi',),
		'hu': ('szerkesztés', 'szerkesztése'),
		'id': ('edit',),
		'it': ('modifica',),
		'kk': ('өңдеу',),
		'ko': ('수정',),
		'ms': ('sunting',),
		'nb': ('rediger',),
		'nl': ('bewerken',),
		'pl': ('edytuj',),
		'pt-br': ('editar',),
		'ro': ('editează',),
		'ru': ('изменить',),
		'sk': ('upraviť',),
		'sr': ('уреди',),
		'sv': ('redigera',),
		'tr': ('düzenle',),
		'uk': ('змінити',),
		'uz': ('tahrirlash',),
		'zh-hans': ('编辑',),
		'zh-hant': ('編輯',),
	},
	'forward': {
		'ar': ('تحويل',),
		'be': ('пераслаць',),
		'ca': ('reenvia',),
		'cs': ('přeposlat',),
		'de': ('weiterleiten',),
		'en': ('forward',),
		'es': ('reenviar',),
		'fa': ('فوروارد',),
		'fi': ('välitä',),
		'fr': ('transférer',),
		'he': ('העבר',),
		'hr': ('proslijedi',),
		'hu': ('továbbítás',),
		'id': ('teruskan',),
		'it': ('inoltra',),
		'kk': ('жөнелту',),
		'ko': ('전달',),
		'ms': ('majukan',),
		'nb': ('videresend',),
		'nl': ('doorsturen',),
		'pl': ('przekaż',),
		'pt-br': ('encaminhar',),
		'ro': ('redirecționează',),
		'ru': ('переслать',),
		'sk': ('preposlať',),
		'sr': ('проследи',),
		'sv': ('vidarebefordra',),
		'tr': ('i̇let',),
		'uk': ('переслати',),
		'uz': ('uzatish',),
		'zh-hans': ('转发',),
		'zh-hant': ('轉傳',),
	},
	'pin': {
		'ar': ('تثبيت', 'إلغاء التثبيت', 'تثبيت في الأعلى'),
		'be': ('замацаваць', 'адмацаваць', 'замацаваць зверху'),
		'ca': ('fixa', 'deixa de fixar', "fixa'l a dalt", 'deixa de fixar-lo'),
		'cs': ('připnout', 'odepnout', 'připnout nahoru', 'odepnout svrchu'),
		'de': ('anheften', 'loslösen', 'oben anheften', 'oben loslösen'),
		'en': ('pin', 'unpin', 'pin to top', 'unpin from top'),
		'es': ('fijar', 'desfijar', 'fijar arriba', 'desfijar de arriba'),
		'fa': ('سنجاق کردن', 'برداشتن سنجاق', 'سنجاق کردن به بالا', 'برداشتن سنجاق از بالا'),
		'fi': ('kiinnitä', 'irrota'),
		'fr': ('épingler', 'désépingler'),
		'he': ('נעץ', 'בטל נעיצה', 'נעץ להתחלה', 'בטל נעיצה להתחלה'),
		'hr': ('prikvači', 'otkvači', 'prikvači na vrh', 'otkvači s vrha'),
		'hu': ('rögzítés', 'rögzítés feloldása', 'rögzítés felül', 'felső rögzítés feloldása'),
		'id': ('sematkan', 'lepas sematan', 'sematkan ke atas'),
		'it': ('fissa', 'togli', 'fissa in alto', "togli dall'alto"),
		'kk': ('бекіту', 'шешу'),
		'ko': ('고정', '고정 해제', '맨 위에 고정', '맨 위 고정 해제'),
		'ms': ('semat', 'turunkan', 'semat ke atas', 'turunkan dari atas'),
		'nb': ('fest', 'løsne', 'fest øverst', 'løsne fra øverst'),
		'nl': ('vastzetten', 'losmaken'),
		'pl': ('przypnij', 'odepnij', 'przypnij na górze', 'odepnij od góry'),
		'pt-br': ('fixar', 'desafixar', 'fixar no topo', 'desafixar do topo'),
		'ro': ('fixează', 'detașează', 'fixează sus', 'detașează de sus'),
		'ru': ('закрепить', 'открепить'),
		'sk': ('pripnúť', 'odopnúť', 'pripnúť na vrch', 'odopnúť z vrchu'),
		'sr': ('закачи', 'откачи', 'закачи на врх', 'откачи с врха'),
		'sv': ('fäst upp', 'lossa', 'fäst överst', 'lossa från ovankanten'),
		'tr': ('sabitle', 'sabitlemeyi kaldır', 'başa sabitle', 'başa sabitlemeyi kaldır'),
		'uk': ('прикріпити', 'відкріпити', 'прикріпити вгорі'),
		'uz': ('qadash', 'yechib olish', 'tepaga qadash', 'yuqoridan yechib olish'),
		'zh-hans': ('置顶', '取消置顶'),
		'zh-hant': ('置頂', '取消置頂'),
	},
	'read': {
		'ar': ('اعتبارها مقروءة', 'اعتبارها غير مقروءة'),
		'be': ('у прачытанае', 'у непрачытанае'),
		'ca': ('marca com a llegit', 'marca-ho per llegir'),
		'cs': ('označit jako přečtené', 'označit jako nepřečtené'),
		'de': ('als gelesen markieren', 'als ungelesen markieren'),
		'en': ('mark as read', 'mark as unread'),
		'es': ('marcar como leído', 'marcar como no leído'),
		'fa': ('علامت زدن به عنوان خوانده شده', 'علامت زدن به عنوان خوانده نشده'),
		'fi': ('merkitse luetuksi', 'merkitse lukemattomaksi'),
		'fr': ('marquer comme lu', 'marquer comme non lu'),
		'he': ('סמן כנקרא', 'סמן כלא נקרא'),
		'hr': ('pročitaj sve', 'označi kao nepročitano'),
		'hu': ('olvasottnak jelöl', 'olvasatlannak jelöl'),
		'id': ('tandai dibaca', 'tandai belum dibaca'),
		'it': ('segna come letto', 'segna come non letto'),
		'kk': ('оқылған', 'жаңа деу'),
		'ko': ('읽음으로 표시', '읽지 않음으로 표시'),
		'ms': ('tanda dah dibaca', 'tanda belum dibaca'),
		'nb': ('merk som lest', 'merk som ulest'),
		'nl': ('markeren als gelezen', 'markeren als ongelezen'),
		'pl': ('oznacz jako przeczytane', 'oznacz jako nieprzeczytane'),
		'pt-br': ('marcar como lido', 'marcar como não lido'),
		'ro': ('marchează ca citit', 'marchează ca necitit'),
		'ru': ('пометить как прочитанное', 'пометить как непрочитанное'),
		'sk': ('označiť ako prečítané', 'označiť ako neprečítané'),
		'sr': ('означи као прочитано', 'означи као непрочитано'),
		'sv': ('markera som läst', 'markera som oläst'),
		'tr': ('okundu olarak işaretle', 'okunmadı olarak işaretle'),
		'uk': ('прочитати', 'позначити як непрочитане'),
		'uz': ('oʻqilgan deb belgilash', 'oʻqilmagan deb belgilash'),
		'zh-hans': ('标记为已读', '标记为未读'),
		'zh-hant': ('標示為已讀', '標示為未讀'),
	},
	'reply': {
		'ar': ('رد', 'الرد في محادثة أخرى'),
		'be': ('адказаць', 'адказаць у іншым чаце'),
		'ca': ('respon', 'respon en un altre xat'),
		'cs': ('odpovědět', 'odpovědět v jiné konverzaci'),
		'de': ('antworten', 'in anderem chat antworten'),
		'en': ('reply', 'reply in another chat'),
		'es': ('responder', 'responder en otro chat'),
		'fa': ('پاسخ', 'پاسخ در گفتگویی دیگر'),
		'fi': ('vastaa', 'vastaa eri keskustelussa'),
		'fr': ('répondre', 'répondre dans un autre échange'),
		'he': ('הגב', "הגב בצ'אט אחר"),
		'hr': ('odgovori', 'odgovori u drugom razgovoru'),
		'hu': ('válasz', 'válasz egy másik csevegésben'),
		'id': ('balas', 'balas dalam obrolan lain'),
		'it': ('rispondi', "rispondi in un'altra chat"),
		'kk': ('жауап', 'басқа чатта жауап беру'),
		'ko': ('답장', '다른 대화에서 답장'),
		'ms': ('balas', 'balas dalam bual lain'),
		'nb': ('svar', 'svar i en annen samtale'),
		'nl': ('antwoorden', 'in andere chat antwoorden'),
		'pl': ('odpowiedz', 'odpowiedz w innym czacie'),
		'pt-br': ('responder', 'responder em outro chat'),
		'ro': ('răspunde', 'răspunde în altă conversație'),
		'ru': ('ответить', 'ответить в другом чате'),
		'sk': ('odpovedať', 'odpovedať v inej konverzácii'),
		'sr': ('одговори', 'одговори у другом ћаскању'),
		'sv': ('svara', 'svara i en annan chatt'),
		'tr': ('yanıtla', 'başka bir sohbette yanıtla'),
		'uk': ('відповісти', 'вибрати інший чат'),
		'uz': ('javob yozish', 'boshqa chatda javob berish'),
		'zh-hans': ('回复', '在另一个聊天中回复'),
		'zh-hant': ('回覆', '在另一個聊天中回覆'),
	},
	'save_as': {
		'ar': ('حفظ كـ...', 'حفظ كـ'),
		'be': ('захаваць як…',),
		'ca': ('anomena i desa…',),
		'cs': ('uložit jako...', 'uložit jako'),
		'de': ('speichern unter…',),
		'en': ('save as...', 'save as'),
		'es': ('guardar como…',),
		'fa': ('ذخیره به عنوان...', 'ذخیره به عنوان'),
		'fi': ('tallenna nimellä...', 'tallenna nimellä'),
		'fr': ('enregistrer sous...', 'enregistrer sous'),
		'he': ('שמור בשם...', 'שמור בשם'),
		'hr': ('spremi kao...', 'spremi kao'),
		'hu': ('mentés másként...', 'mentés másként'),
		'id': ('simpan sebagai ...', 'simpan sebagai'),
		'it': ('salva come...', 'salva come'),
		'kk': ('сақтау',),
		'ko': ('다른 이름으로 저장...', '다른 이름으로 저장'),
		'ms': ('simpan sebagai...', 'simpan sebagai'),
		'nb': ('lagre som…',),
		'nl': ('opslaan als...', 'opslaan als'),
		'pl': ('zapisz jako…',),
		'pt-br': ('salvar como...', 'salvar como'),
		'ro': ('salvează ca...', 'salvează ca'),
		'ru': ('сохранить как...', 'сохранить как'),
		'sk': ('uložiť ako...', 'uložiť ako'),
		'sr': ('сачувај као...', 'сачувај као'),
		'sv': ('spara som...', 'spara som'),
		'tr': ('farklı kaydet…',),
		'uk': ('зберегти як...', 'зберегти як'),
		'uz': ('saqlab olish...', 'saqlab olish'),
		'zh-hans': ('另存为…',),
		'zh-hant': ('另存為...', '另存為'),
	},
	'select': {
		'ar': ('تحديد',),
		'be': ('выбраць',),
		'ca': ('selecciona',),
		'cs': ('vybrat',),
		'de': ('auswählen',),
		'en': ('select',),
		'es': ('seleccionar',),
		'fa': ('انتخاب',),
		'fi': ('valitse',),
		'fr': ('sélectionner',),
		'he': ('בחר',),
		'hr': ('označi',),
		'hu': ('kijelöl',),
		'id': ('pilih',),
		'it': ('seleziona',),
		'kk': ('таңдау',),
		'ko': ('선택',),
		'ms': ('pilih',),
		'nb': ('velg',),
		'nl': ('selecteren',),
		'pl': ('zaznacz',),
		'pt-br': ('selecionar',),
		'ro': ('selectează',),
		'ru': ('выбрать',),
		'sk': ('vybrať',),
		'sr': ('изабери',),
		'sv': ('markera',),
		'tr': ('seç',),
		'uk': ('вибрати',),
		'uz': ('tanlash',),
		'zh-hans': ('选择',),
		'zh-hant': ('選取',),
	},
}

# Legacy font icon glyphs for context menu options (for backwards compatibility).
# Format: "action": "unicode_char"
icons_from_context_menu = {
	"attach": "\ue7c0",
	"unpin": "\ue77a",
	"reply": "\ue248",
	"copy": "\ue8c8",
	"edit": "\ue104",
	"forward": "\ue72d",
	"delete": "\ue74d",
	"save_as": "\ue792",
	"select": "\ue97e",
	"read": "\ue91d",
	"unread": "\ue91c",
}


# ============================================================================
# 5. BUTTONS, ICONS & MEDIA
# ============================================================================

# Spoken labels for buttons with technical IDs or missing names.
# Format: "technical_id": _("spoken_label")
labels_for_buttons = {
	"Back": _("Back"),
	"Menu": _("Menu"),
	"Pin": _("Attach"),
	"Edit": _("Edit"),
	"Photo": _("Photo"),
	"Image": _("Image"),
	"InviteLink": _("Invite link"),
	"FieldSeconds": _("Choose time"),
	"TitleField": _("Title field"),
}

# Spoken labels for icon-only buttons without text names.
# Format: "unicode_icon": _("spoken_label")
labels_in_buttons = {
	"\ue987": _("Go to next reaction"),
	"\ue76e": _("Insert emojis"),
	"\ue10b": _("Done"),
	"\ue722": _("Next"),
	"\ue90c": _("Merge files"),
	"\ue721": _("Search"),
	"\ue74d": _("Delete"),
	"\ue711": _("Close"),
}

# Keywords indicating active download/upload transfer state in media buttons.
# Format: "lang_code": ("keyword", ...)
active_download_keywords = {
	'ar': ('إلغاء',),
	'be': ('скасаваць',),
	'ca': ('cancel·la',),
	'cs': ('zrušit',),
	'de': ('abbrechen',),
	'en': ('cancel',),
	'es': ('cancelar',),
	'fa': ('لغو',),
	'fi': ('peruuta',),
	'fr': ('annuler',),
	'he': ('ביטול',),
	'hr': ('odustani',),
	'hu': ('mégsem',),
	'id': ('batal',),
	'it': ('annulla',),
	'kk': ('артқа',),
	'ko': ('취소',),
	'ms': ('batal',),
	'nb': ('avbryt',),
	'nl': ('terug',),
	'pl': ('anuluj',),
	'pt-br': ('cancelar',),
	'ro': ('anulare',),
	'ru': ('отмена',),
	'sk': ('zrušiť',),
	'sr': ('откажи',),
	'sv': ('avbryt',),
	'tr': ('i̇ptal et',),
	'uk': ('скасувати',),
	'uz': ('bekor qilish',),
	'zh-hans': ('取消',),
	'zh-hant': ('取消',),
}
